# Generated by Django 3.2.25 on 2025-02-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedThreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=100)),
                ('vendor_project', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('threat_name', models.CharField(max_length=200)),
                ('date_added', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('required_action', models.TextField()),
                ('due_date', models.CharField(max_length=100)),
                ('pub_date', models.CharField(max_length=100)),
                ('cvss', models.CharField(max_length=10)),
                ('cwe', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('complexity', models.CharField(max_length=50)),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
                ('analyzed', models.BooleanField(default=False)),
                ('prediction_result', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cyber_threat_type_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_of_ongoing_cyber_attacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=300)),
                ('vendor_project', models.CharField(max_length=300)),
                ('product', models.CharField(max_length=300)),
                ('threat_name', models.CharField(max_length=300)),
                ('date_added', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=300)),
                ('required_action', models.CharField(max_length=300)),
                ('due_date', models.CharField(max_length=300)),
                ('pub_date', models.CharField(max_length=300)),
                ('cvss', models.CharField(max_length=300)),
                ('cwe', models.CharField(max_length=300)),
                ('Type', models.CharField(max_length=300)),
                ('complexity', models.CharField(max_length=300)),
                ('Prediction', models.CharField(max_length=300)),
            ],
        ),
    ]
